env:
    browser: true
    es2021: true
extends:
    - 'plugin:react/recommended'
    - airbnb
    - prettier
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 12
    sourceType: module
plugins:
    - react
rules:
    {
        'react/jsx-filename-extension':
            [2, { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }],
        'jsx-a11y/label-has-associated-control':
            ['error', { 'required': { 'some': ['nesting', 'id'] } }],
        'jsx-a11y/label-has-for':
            ['error', { 'required': { 'some': ['nesting', 'id'] } }],
        'react/jsx-props-no-spreading': 0,
        'react/require-default-props': 0,
        'no-unused-vars': 1,
    }
